### PR TITLE
Node 12 fixes

### LINKED ISSUE #74: Fails to build on node v12
```
gyp info using node-gyp@3.8.0
gyp info using node@12.4.0 | darwin | x64
```

Build with node-gyp fails on node v12, but works fine on node v11. Any ideas why?

### PR DESCRIPTION
**Pull request by dudleycarr**
This isn't in place of the work to move to N-API. This is simply to address the breaking changes in NodeJS 12 with respect to NAN.

I should note that this change does drop support for Node versions below 6 due to changes in Node-GYP. Those versions are now long out of LTS support. 

* Migrate to new NaN APIs
* Use new Buffer API to avoid NodeJS deprecated warnings
* Upgrade NaN, Node-GYP and bindings versions.
* Bump package version to 5.4

Fixes #74

### CODE REVIEW

**Comment by dudleycarr** [comment]
ping

**Comment by anandsuresh** [comment]
@dudleycarr Thanks for getting this done. Will release a new version soon.

**Comment by karlnorling** [comment]
@anandsuresh ping - when are you doing a release?

**Comment by anandsuresh** [comment]
This was merged and released 2 months ago. v6 of the package should contain these changes. Let me know if you see otherwise.

**Pull request merged**
