### PR TITLE
Move over to N-API from NAN

### PR DESCRIPTION
**Pull request by anandsuresh**

### CODE REVIEW

**Comment by anandsuresh** [comment]
@NickNaso What would be a good next step? Should we make a PR against the NAPI repo linking this branch to the list of NAPI modules?

**Comment by NickNaso** [comment]
Hi @anandsuresh I linked the issue [BAPI Support](https://github.com/anandsuresh/sse4_crc32/issues/69) with an issue on the **abi-stable-node** repo  [https://github.com/nodejs/abi-stable-node/issues/246 ](https://github.com/nodejs/abi-stable-node/issues/246). In this issue we report our porting activities and if you want fell free to report your experience with N-API. 
For the  **sse4_crc32** module we can publish a tagged version of the module as reported here in this guide [https://nodejs.org/en/docs/guides/publishing-napi-modules/](https://nodejs.org/en/docs/guides/publishing-napi-modules/) this means that people can start using the N-API version of the module today if they install like reported below:
`npm install sse4_crc32@n-api`

**Comment by zbjornson** [comment]
@anandsuresh it looks like this is based on an old commit, based on the diff. Are you still planning to move forward with this? There's some code cleanup (around the native build, quite a bit of code that can be removed) that I'd love to contribute, but don't want to mess up your N-API work. On the other hand, you might have an easier time converting to N-API with my proposed cleanup.

**Comment by anandsuresh** [comment]
Sure. I haven't had a lot of time to focus on this. If you have any code to
contribute, that would be awesome.

**Comment by ivan** [comment]
I have updated this PR over at https://github.com/ludios/sse4_crc32/commits/master and I am testing it, feel free to take my commits.

**Comment by stephenplusplus** [comment]
@anandsuresh Hello! Any thoughts on how we should proceed with this migration?

**Comment by stephenplusplus** [comment]
@ivan would you be willing to send your changes as a PR here? Whatever we can do to make it easier for @anandsuresh to merge and release 🙏

**Comment by anandsuresh** [comment]
Whoops. Sorry guys. Been a little busy lately.

I should have some down-time this week to look this over and get it
merged. Let me know if there is anything else that I can help with.

Thanks

Anand

**Comment by ivan** [comment]
@anandsuresh FYI I think there's a UAF here that I fixed with https://github.com/ludios/sse4_crc32/commit/d39bdd7e22054883e203c8c6f20c4a8e9c75e3c9

**Comment by anandsuresh** [comment]
Thanks @NickNaso for getting this started, and to @ivan for the fixes. With v6, the package is now available on NPM as well as GitHub Package Registry! Apologies for delays at my end.

**Pull request merged**
